- name: Creates directory for scripts operations
  file: path=/root/.ssh/keys state=directory

- name: Copy script to server
  copy: src=files/parsekeys.py dest=/root/.ssh/keys/parsekeys.py

- name: Run script to Add ssh users keys to a remote server
  command: python /root/.ssh/keys/parsekeys.py

- name: Delete a temp directory directory
  command:  rm -rf /root/.ssh/keys 

- name: Remove old ssh keys from server
  lineinfile: dest=/root/.ssh/authorized_keys regexp="{{ item }}$" state=absent
  with_items:
  - lazypanda
  - necros

