- set_fact: htpasswd_path=/etc/squid/htpasswd

- set_fact: eth0_active=true
  when: ansible_default_ipv4.alias == "eth0"

- set_fact: eth1_active=true
  when: ansible_default_ipv4.alias == "eth1"

- assert: { that: "'{{ ansible_distribution_major_version }}' == '7' and '{{ ansible_os_family }}' == 'Debian'" }

- name: Install squid
  apt: name=squid state=latest

- name: Copy qquid config
  copy: src=files/squid.conf dest=/etc/squid/squid.conf

- name: Create directory for additional users
  file: path=/etc/squid/users state=directory

- name: Copy script generate_user.py to server 
  copy: src=files/generate_user.py dest=/etc/squid/generate_user.py owner=root group=root mode=0755

- name: Add main IP to squid conf and create user
  command: /etc/squid/generate_user.py {{ ansible_default_ipv4.address }}

- name: Add additional IPs to squid.conf and create users eth0
  command: /etc/squid/generate_user.py {{ item.address }}
  with_items: 
        - "{{ ansible_eth0.ipv4_secondaries }}"
  when: eth0_active is defined and ansible_eth0.ipv4_secondaries is defined
  
- name: Add additional IPs to squid.conf and create users eth1
  command: /etc/squid/generate_user.py {{ item.address }}
  with_items: 
        - "{{ ansible_eth1.ipv4_secondaries }}"
  when: eth1_active is defined and ansible_eth1.ipv4_secondaries is defined
  
- name: Service start
  service: name=squid state=started

- name: Service enable
  service: name=squid enabled=yes

- name: The squid passwords located here /etc/squid/passwd_holder
  shell: cat /etc/squid/passwd_holder
  register: squidpasswd

- name: Print squid passwords
  debug: var=squidpasswd.stdout_lines

